# Docker Compose Configuration for KABZS EVENT
# This is a template - Laravel Sail will generate its own version

version: '3.8'

services:
    # PHP & Nginx Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kabzs-event-app
        container_name: kabzs-event-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - kabzs-network
        depends_on:
            - mysql
            - redis

    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: kabzs-event-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: event_management_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        networks:
            - kabzs-network

    # Redis Cache & Queue
    redis:
        image: redis:alpine
        container_name: kabzs-event-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - kabzs-network

    # Mailpit (Email Testing)
    mailpit:
        image: axllent/mailpit
        container_name: kabzs-event-mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - kabzs-network

    # Nginx Web Server
    nginx:
        image: nginx:alpine
        container_name: kabzs-event-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - kabzs-network
        depends_on:
            - app

networks:
    kabzs-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local

